

CREATE SEQUENCE SEQ_KART_CARI_ID
  START WITH 1001
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_LOGIN_KULLANICI_ID
  START WITH 2
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE SEQ_SIPARIS_DOSYA_ID
  START WITH 61
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_STOK_ID
  START WITH 1021
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE TABLE LOG_TANIM_BIRIM
(
  LOG_OP        CHAR(1 BYTE),
  LOG_TIME      DATE,
  LOG_SCHEMA    VARCHAR2(30 BYTE),
  LOG_TERMINAL  VARCHAR2(16 BYTE),
  LOG_USER      VARCHAR2(30 BYTE),
  LOG_IP        VARCHAR2(30 BYTE),
  BIRIM         VARCHAR2(5 BYTE),
  BIRIM_AD      VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LOG_SIPARIS_DOSYA
(
  LOG_OP          CHAR(1 BYTE),
  LOG_TIME        DATE,
  LOG_SCHEMA      VARCHAR2(30 BYTE),
  LOG_TERMINAL    VARCHAR2(16 BYTE),
  LOG_USER        VARCHAR2(30 BYTE),
  LOG_IP          VARCHAR2(30 BYTE),
  SIPARIS_ID      NUMBER,
  CARI_ID         NUMBER,
  BIRIM           VARCHAR2(5 BYTE),
  STOK_ID         NUMBER,
  MIKTAR          NUMBER(10,2),
  SIPARIS_TARIHI  DATE,
  SIPARIS_TUR     CHAR(1 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LOG_KART_STOK
(
  LOG_OP                   CHAR(1 BYTE),
  LOG_TIME                 DATE,
  LOG_SCHEMA               VARCHAR2(30 BYTE),
  LOG_TERMINAL             VARCHAR2(16 BYTE),
  LOG_USER                 VARCHAR2(30 BYTE),
  LOG_IP                   VARCHAR2(30 BYTE),
  STOK_ID                  NUMBER,
  STOK_AD                  VARCHAR2(20 BYTE),
  BIRIM                    VARCHAR2(5 BYTE),
  OZEL_KOD                 VARCHAR2(20 BYTE),
  ALINAN_SIPARIS_MIKTARI   NUMBER(10,2),
  VERILEN_SIPARIS_MIKTARI  NUMBER(10,2)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LOGIN_KULLANICI
(
  ID             NUMBER,
  KULLANICI_ADI  VARCHAR2(50 CHAR)              NOT NULL,
  SIFRE          VARCHAR2(50 CHAR)              NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE LOG_KART_CARI
(
  LOG_OP        CHAR(1 BYTE),
  LOG_TIME      DATE,
  LOG_SCHEMA    VARCHAR2(30 BYTE),
  LOG_TERMINAL  VARCHAR2(16 BYTE),
  LOG_USER      VARCHAR2(30 BYTE),
  LOG_IP        VARCHAR2(30 BYTE),
  CARI_ID       NUMBER,
  CARI_SIRKET   VARCHAR2(50 BYTE),
  CARI_TIP      VARCHAR2(1 BYTE),
  OZEL_KOD      VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE SIPARIS_DOSYA
(
  SIPARIS_ID      NUMBER,
  CARI_ID         NUMBER                        NOT NULL,
  BIRIM           VARCHAR2(5 BYTE)              NOT NULL,
  STOK_ID         NUMBER                        NOT NULL,
  MIKTAR          NUMBER(10,2)                  NOT NULL,
  SIPARIS_TARIHI  DATE                          DEFAULT SYSDATE               NOT NULL,
  SIPARIS_TUR     CHAR(1 BYTE)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE KART_CARI
(
  CARI_ID      NUMBER,
  CARI_SIRKET  VARCHAR2(50 BYTE)                NOT NULL,
  CARI_TIP     VARCHAR2(1 BYTE)                 NOT NULL,
  OZEL_KOD     VARCHAR2(20 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE KART_STOK
(
  STOK_ID                  NUMBER,
  STOK_AD                  VARCHAR2(20 BYTE)    NOT NULL,
  BIRIM                    VARCHAR2(5 BYTE)     NOT NULL,
  OZEL_KOD                 VARCHAR2(20 BYTE),
  ALINAN_SIPARIS_MIKTARI   NUMBER(10,2)         DEFAULT 0                     NOT NULL,
  VERILEN_SIPARIS_MIKTARI  NUMBER(10,2)         DEFAULT 0                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE TANIM_BIRIM
(
  BIRIM     VARCHAR2(5 BYTE),
  BIRIM_AD  VARCHAR2(20 BYTE)                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX PK_SIPARIS ON SIPARIS_DOSYA
(SIPARIS_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_KART_CARI ON KART_CARI
(CARI_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_KART_STOK ON KART_STOK
(STOK_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX PK_TANIM_BIRIM ON TANIM_BIRIM
(BIRIM)
LOGGING
NOPARALLEL;


CREATE OR REPLACE PROCEDURE       SIPARIS_EKLE (
  P_ISLEM_TURU     IN CHAR,
  P_SIPARIS_ID     IN NUMBER,
  P_CARI_ID        IN NUMBER,
  P_BIRIM          IN VARCHAR2,
  P_STOK_ID        IN NUMBER,
  P_MIKTAR         IN NUMBER,
  P_SIPARIS_TARIHI IN DATE,
  P_SIPARIS_TUR    IN CHAR
)
IS
BEGIN
  IF P_ISLEM_TURU NOT IN ('I', 'U') THEN
    RAISE_APPLICATION_ERROR(-20001, 'P_ISLEM_TURU sadece ''I'' (INSERT) veya ''U'' (UPDATE) olabilir.');
  END IF;

  IF UPPER(P_SIPARIS_TUR) NOT IN ('A', 'V') THEN
    RAISE_APPLICATION_ERROR(-20002, 'P_SIPARIS_TUR sadece ''A'' (Al m) veya ''V'' (Verilen) olabilir.');
  END IF;

  IF P_ISLEM_TURU = 'I' THEN
    INSERT INTO YUSUF.SIPARIS_DOSYA (
      CARI_ID, BIRIM, STOK_ID, MIKTAR, SIPARIS_TARIHI, SIPARIS_TUR
    ) VALUES (
      P_CARI_ID, P_BIRIM, P_STOK_ID, P_MIKTAR, P_SIPARIS_TARIHI, UPPER(P_SIPARIS_TUR)
    );

  ELSIF P_ISLEM_TURU = 'U' THEN
    UPDATE YUSUF.SIPARIS_DOSYA
    SET
      CARI_ID        = P_CARI_ID,
      BIRIM          = P_BIRIM,
      STOK_ID        = P_STOK_ID,
      MIKTAR         = P_MIKTAR,
      SIPARIS_TARIHI = P_SIPARIS_TARIHI,
      SIPARIS_TUR    = UPPER(P_SIPARIS_TUR)
    WHERE SIPARIS_ID = P_SIPARIS_ID;
  END IF;
END;
/

SHOW ERRORS;


CREATE OR REPLACE PROCEDURE       ESITLE_STOK_MIKTAR
IS
BEGIN
  MERGE INTO KART_STOK KS
  USING (
    SELECT
      KS.STOK_ID AS STOK_ID,
      NVL(SD.ALINAN, 0) AS ALINAN,
      NVL(SD.VERILEN, 0) AS VERILEN
    FROM KART_STOK KS
    LEFT JOIN (
      SELECT
        STOK_ID,
        SUM(CASE WHEN SIPARIS_TUR = 'A' THEN MIKTAR ELSE 0 END) AS ALINAN,
        SUM(CASE WHEN SIPARIS_TUR = 'V' THEN MIKTAR ELSE 0 END) AS VERILEN
      FROM SIPARIS_DOSYA
      GROUP BY STOK_ID
    ) SD
    ON KS.STOK_ID = SD.STOK_ID
  ) SD
  ON (KS.STOK_ID = SD.STOK_ID)
  WHEN MATCHED THEN
    UPDATE SET
      KS.ALINAN_SIPARIS_MIKTARI  = SD.ALINAN,
      KS.VERILEN_SIPARIS_MIKTARI = SD.VERILEN;
END ESITLE_STOK_MIKTAR;
/

SHOW ERRORS;


CREATE OR REPLACE FUNCTION       CARI_TOPLAM_SIPARIS (
  P_CARI_ID IN NUMBER
) RETURN NUMBER
IS
  P_TOPLAM_MIKTAR NUMBER(10,2);
BEGIN
  SELECT NVL((
  SELECT NVL(SUM(MIKTAR), 0)
  FROM SIPARIS_DOSYA
  WHERE CARI_ID = P_CARI_ID),0)   INTO P_TOPLAM_MIKTAR FROM DUAL;
  RETURN NVL(P_TOPLAM_MIKTAR,0);
END;
/

SHOW ERRORS;


CREATE OR REPLACE VIEW VW_CARI_SIPARIS_LISTE
AS 
SELECT 
  S.SIPARIS_ID,
  S.MIKTAR,
  C.CARI_SIRKET,
  C.CARI_TIP
FROM SIPARIS_DOSYA S
RIGHT JOIN KART_CARI C ON S.CARI_ID = C.CARI_ID;


CREATE OR REPLACE VIEW VW_STOK_TOPLAM_SIPARIS
AS 
SELECT 
  ST.STOK_AD,
  NVL(SUM(S.MIKTAR), 0) AS TOPLAM
FROM KART_STOK ST
LEFT JOIN SIPARIS_DOSYA S ON ST.STOK_ID = S.STOK_ID
GROUP BY ST.STOK_AD;


CREATE OR REPLACE VIEW VW_EKSI_STOKLAR
AS 
SELECT 
  ST.STOK_AD,
  SUM(CASE WHEN S.SIPARIS_TUR = 'V' THEN S.MIKTAR ELSE 0 END) -
  SUM(CASE WHEN S.SIPARIS_TUR = 'A' THEN S.MIKTAR ELSE 0 END) AS NET_MIKTAR
FROM KART_STOK ST
LEFT JOIN SIPARIS_DOSYA S ON S.STOK_ID = ST.STOK_ID
GROUP BY ST.STOK_AD
HAVING (
  SUM(CASE WHEN S.SIPARIS_TUR = 'V' THEN S.MIKTAR ELSE 0 END) -
  SUM(CASE WHEN S.SIPARIS_TUR = 'A' THEN S.MIKTAR ELSE 0 END)
) < 0;


CREATE OR REPLACE TRIGGER ARTIS_KART_CARI_ID
BEFORE INSERT ON KART_CARI
FOR EACH ROW
BEGIN
  :NEW.CARI_ID := SEQ_KART_CARI_ID.NEXTVAL;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER ARTIS_KART_STOK_ID
BEFORE INSERT ON KART_STOK
FOR EACH ROW
BEGIN
  :NEW.STOK_ID := SEQ_STOK_ID.NEXTVAL;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER ARTIS_SIPARIS_ID
BEFORE INSERT ON SIPARIS_DOSYA
FOR EACH ROW
BEGIN
  :NEW.SIPARIS_ID := SEQ_SIPARIS_DOSYA_ID.NEXTVAL;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER SIPARIS_SENKRON
AFTER INSERT OR DELETE ON SIPARIS_DOSYA FOR EACH ROW
BEGIN

  IF INSERTING THEN
    IF :NEW.SIPARIS_TUR = 'A' THEN
      UPDATE KART_STOK
      SET ALINAN_SIPARIS_MIKTARI = ALINAN_SIPARIS_MIKTARI + :NEW.MIKTAR
      WHERE STOK_ID = :NEW.STOK_ID;
    ELSIF :NEW.SIPARIS_TUR = 'V' THEN
      UPDATE KART_STOK
      SET VERILEN_SIPARIS_MIKTARI = VERILEN_SIPARIS_MIKTARI + :NEW.MIKTAR
      WHERE STOK_ID = :NEW.STOK_ID;
    END IF;
  ELSIF DELETING THEN
    IF :OLD.SIPARIS_TUR = 'A' THEN
      UPDATE KART_STOK
      SET ALINAN_SIPARIS_MIKTARI = ALINAN_SIPARIS_MIKTARI - :OLD.MIKTAR
      WHERE STOK_ID = :OLD.STOK_ID;
    ELSIF :OLD.SIPARIS_TUR = 'V' THEN
      UPDATE KART_STOK
      SET VERILEN_SIPARIS_MIKTARI = VERILEN_SIPARIS_MIKTARI - :OLD.MIKTAR
      WHERE STOK_ID = :OLD.STOK_ID;
    END IF;
  ELSIF UPDATING THEN
    IF :OLD.SIPARIS_TUR = 'A' THEN
      UPDATE KART_STOK
      SET ALINAN_SIPARIS_MIKTARI = ALINAN_SIPARIS_MIKTARI - :OLD.MIKTAR + :NEW.MIKTAR
      
      WHERE STOK_ID = :OLD.STOK_ID;
    ELSIF :OLD.SIPARIS_TUR = 'V' THEN
      UPDATE KART_STOK
      SET VERILEN_SIPARIS_MIKTARI = VERILEN_SIPARIS_MIKTARI - :OLD.MIKTAR + :NEW.MIKTAR
      WHERE STOK_ID = :OLD.STOK_ID;
    END IF;  
  END IF;
END;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER PLOG_KART_CARI
AFTER INSERT OR UPDATE OR DELETE ON KART_CARI FOR EACH ROW
DECLARE
  TMP CHAR(1);
  v_log_schema   VARCHAR2(30);
  v_log_terminal VARCHAR2(16);
  v_log_user     VARCHAR2(30);
  v_log_ip       VARCHAR2(30);
BEGIN
  SELECT schemaname, terminal, osuser, SYS_CONTEXT('USERENV', 'IP_ADDRESS')
  INTO v_log_schema, v_log_terminal, v_log_user, v_log_ip
  FROM v$session
  WHERE SID = (SELECT SYS_CONTEXT('USERENV', 'SID') FROM DUAL);

  IF INSERTING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_KART_CARI (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, CARI_ID, CARI_SIRKET, CARI_TIP, OZEL_KOD)
      VALUES ('I', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :NEW.CARI_ID, :NEW.CARI_SIRKET, :NEW.CARI_TIP, :NEW.OZEL_KOD);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  ELSIF UPDATING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_KART_CARI (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, CARI_ID, CARI_SIRKET, CARI_TIP, OZEL_KOD)
      VALUES ('U', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :OLD.CARI_ID, :OLD.CARI_SIRKET, :OLD.CARI_TIP, :OLD.OZEL_KOD);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  ELSIF DELETING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_KART_CARI (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, CARI_ID, CARI_SIRKET, CARI_TIP, OZEL_KOD)
      VALUES ('D', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :OLD.CARI_ID, :OLD.CARI_SIRKET, :OLD.CARI_TIP, :OLD.OZEL_KOD);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  END IF;
END PLOG_KART_CARI;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER PLOG_KART_STOK
AFTER INSERT OR UPDATE OR DELETE ON KART_STOK FOR EACH ROW
DECLARE
  TMP CHAR(1);
  v_log_schema   VARCHAR2(30);
  v_log_terminal VARCHAR2(16);
  v_log_user     VARCHAR2(30);
  v_log_ip       VARCHAR2(30);
BEGIN
  SELECT schemaname, terminal, osuser, SYS_CONTEXT('USERENV', 'IP_ADDRESS')
  INTO v_log_schema, v_log_terminal, v_log_user, v_log_ip
  FROM v$session
  WHERE SID = (SELECT SYS_CONTEXT('USERENV', 'SID') FROM DUAL);

  IF INSERTING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_KART_STOK (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, STOK_ID, STOK_AD, BIRIM, OZEL_KOD, ALINAN_SIPARIS_MIKTARI, VERILEN_SIPARIS_MIKTARI)
      VALUES ('I', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :NEW.STOK_ID, :NEW.STOK_AD, :NEW.BIRIM, :NEW.OZEL_KOD, :NEW.ALINAN_SIPARIS_MIKTARI, :NEW.VERILEN_SIPARIS_MIKTARI);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  ELSIF UPDATING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_KART_STOK (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, STOK_ID, STOK_AD, BIRIM, OZEL_KOD, ALINAN_SIPARIS_MIKTARI, VERILEN_SIPARIS_MIKTARI)
      VALUES ('U', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :OLD.STOK_ID, :OLD.STOK_AD, :OLD.BIRIM, :OLD.OZEL_KOD, :OLD.ALINAN_SIPARIS_MIKTARI, :OLD.VERILEN_SIPARIS_MIKTARI);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  ELSIF DELETING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_KART_STOK (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, STOK_ID, STOK_AD, BIRIM, OZEL_KOD, ALINAN_SIPARIS_MIKTARI, VERILEN_SIPARIS_MIKTARI)
      VALUES ('D', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :OLD.STOK_ID, :OLD.STOK_AD, :OLD.BIRIM, :OLD.OZEL_KOD, :OLD.ALINAN_SIPARIS_MIKTARI, :OLD.VERILEN_SIPARIS_MIKTARI);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  END IF;
END PLOG_KART_STOK;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER PLOG_SIPARIS_DOSYA
AFTER INSERT OR UPDATE OR DELETE ON SIPARIS_DOSYA FOR EACH ROW
DECLARE
  TMP CHAR(1);
  v_log_schema   VARCHAR2(30);
  v_log_terminal VARCHAR2(16);
  v_log_user     VARCHAR2(30);
  v_log_ip       VARCHAR2(30);
BEGIN
  SELECT schemaname, terminal, osuser, SYS_CONTEXT('USERENV', 'IP_ADDRESS')
  INTO v_log_schema, v_log_terminal, v_log_user, v_log_ip
  FROM v$session
  WHERE SID = (SELECT SYS_CONTEXT('USERENV', 'SID') FROM DUAL);

  IF INSERTING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_SIPARIS_DOSYA (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, SIPARIS_ID, CARI_ID, BIRIM, STOK_ID, MIKTAR, SIPARIS_TARIHI, SIPARIS_TUR)
      VALUES ('I', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :NEW.SIPARIS_ID, :NEW.CARI_ID, :NEW.BIRIM, :NEW.STOK_ID, :NEW.MIKTAR, :NEW.SIPARIS_TARIHI, :NEW.SIPARIS_TUR);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  ELSIF UPDATING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_SIPARIS_DOSYA (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, SIPARIS_ID, CARI_ID, BIRIM, STOK_ID, MIKTAR, SIPARIS_TARIHI, SIPARIS_TUR)
      VALUES ('U', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :OLD.SIPARIS_ID, :OLD.CARI_ID, :OLD.BIRIM, :OLD.STOK_ID, :OLD.MIKTAR, :OLD.SIPARIS_TARIHI, :OLD.SIPARIS_TUR);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  ELSIF DELETING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_SIPARIS_DOSYA (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, SIPARIS_ID, CARI_ID, BIRIM, STOK_ID, MIKTAR, SIPARIS_TARIHI, SIPARIS_TUR)
      VALUES ('D', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :OLD.SIPARIS_ID, :OLD.CARI_ID, :OLD.BIRIM, :OLD.STOK_ID, :OLD.MIKTAR, :OLD.SIPARIS_TARIHI, :OLD.SIPARIS_TUR);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  END IF;
END PLOG_SIPARIS_DOSYA;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER PLOG_TANIM_BIRIM
AFTER INSERT OR UPDATE OR DELETE ON TANIM_BIRIM FOR EACH ROW
DECLARE
  TMP CHAR(1);
  v_log_schema   VARCHAR2(30);
  v_log_terminal VARCHAR2(16);
  v_log_user     VARCHAR2(30);
  v_log_ip       VARCHAR2(30);
BEGIN
  SELECT schemaname, terminal, osuser, SYS_CONTEXT('USERENV', 'IP_ADDRESS')
  INTO v_log_schema, v_log_terminal, v_log_user, v_log_ip
  FROM v$session
  WHERE SID = (SELECT SYS_CONTEXT('USERENV', 'SID') FROM DUAL);

  IF INSERTING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_TANIM_BIRIM (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, BIRIM, BIRIM_AD)
      VALUES ('I', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :NEW.BIRIM, :NEW.BIRIM_AD);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  ELSIF UPDATING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_TANIM_BIRIM (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, BIRIM, BIRIM_AD)
      VALUES ('U', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :OLD.BIRIM, :OLD.BIRIM_AD);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  ELSIF DELETING THEN
    BEGIN
      INSERT INTO YUSUF.LOG_TANIM_BIRIM (LOG_OP, LOG_TIME, LOG_SCHEMA, LOG_TERMINAL, LOG_USER, LOG_IP, BIRIM, BIRIM_AD)
      VALUES ('D', SYSDATE, v_log_schema, v_log_terminal, v_log_user, v_log_ip, :OLD.BIRIM, :OLD.BIRIM_AD);
    EXCEPTION WHEN OTHERS THEN TMP := 'X'; END;
  END IF;
END PLOG_TANIM_BIRIM;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER TRG_LOGIN_KULLANICI_ID
BEFORE INSERT ON LOGIN_KULLANICI
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_LOGIN_KULLANICI_ID.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/
SHOW ERRORS;


ALTER TABLE LOGIN_KULLANICI ADD (
  PRIMARY KEY
 (ID));

ALTER TABLE SIPARIS_DOSYA ADD (
  CONSTRAINT CHK_SIPARIS_TUR
 CHECK (SIPARIS_TUR IN ('A', 'V')),
  CONSTRAINT PK_SIPARIS
 PRIMARY KEY
 (SIPARIS_ID));

ALTER TABLE KART_CARI ADD (
  CONSTRAINT CHK_CARI_TIPI
 CHECK (CARI_TIP IN ('A', 'V')),
  CONSTRAINT PK_KART_CARI
 PRIMARY KEY
 (CARI_ID));

ALTER TABLE KART_STOK ADD (
  CONSTRAINT PK_KART_STOK
 PRIMARY KEY
 (STOK_ID));

ALTER TABLE TANIM_BIRIM ADD (
  CONSTRAINT PK_TANIM_BIRIM
 PRIMARY KEY
 (BIRIM));

ALTER TABLE SIPARIS_DOSYA ADD (
  CONSTRAINT FK_SIPARIS_BIRIM 
 FOREIGN KEY (BIRIM) 
 REFERENCES TANIM_BIRIM (BIRIM),
  CONSTRAINT FK_SIPARIS_STOK 
 FOREIGN KEY (STOK_ID) 
 REFERENCES KART_STOK (STOK_ID),
  CONSTRAINT FK_SIPARIS_CARI 
 FOREIGN KEY (CARI_ID) 
 REFERENCES KART_CARI (CARI_ID));

ALTER TABLE KART_STOK ADD (
  CONSTRAINT FK_KART_STOK_BIRIM 
 FOREIGN KEY (BIRIM) 
 REFERENCES TANIM_BIRIM (BIRIM));

